---
title: "Capstone Project"
author: "Tanner Sax"
date: "October 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Proposal

Startup Organizations

Startup organizations have been appearing all over the nation. They have already made huge advances in industries 
across the board and continue to do so. These companies are very exciting and can potentially return a large payout 
to employees from stock options if the venture becomes successful. They are attracting top talent ranging from former 
executives to recent grads. I would like to analyze the top attributes/skills/locations/education/etc. of these hires. 
This analysis will benefit those looking to join a startup organization, whether as a current student, recent graduate 
or a current professional contemplating a company shift. It will allow potential candidates to become more employable 
to work for a startup. The analysis may impact decisions regarding college major choice, pursuit of certifications, 
location, work experience, and self-taught knowledge.

The dataset would need to include employee data from companies that meet criteria to be labeled a startup. As there is 
not a clear-cut definition of what constitutes a startup, some assumptions will need to be made. For this project, 
LinkedIn's 2018 Top Startups list will be used to define the criteria that constitutes a startup. Companies must be 
independent and privately held, have 50 or more employees, be 7 years old or younger, and be headquartered in the 
country on whose list they appear. The dataset will be built from scraping techniques on LinkedIn. It will include 
names, location, summary, number of connections, and skills/endorsements of employees that work for companies on the 
Top 50 Startups list. The dataset will give insights into the most common majors, certifications, location, and 
work experience of these employees. The final project will be in the format of an R Markdown document, which will 
consist of the dataset, code written in R programming language, a report on the findings/insights gained, and 
visualizations of different graphs/charts to illustrate the insights.

https://www.linkedin.com/pulse/linkedin-top-startups-2018-50-most-sought-after-us-daniel-roth/

